<?php
// $Id$
/**
* Supports TOPS integration with Drupal
* @file
**/

// initialize autoloaders and dependency injection
$drupalAutoloader = require_once(__DIR__.'/../../../../lib/Tops/start/autoload.php');
require_once(__DIR__.'/../../../../lib/Tops/start/init.php');

/**
 * Implements hook_menu().
 */
function tops_menu()
{
    return \Drupal\tops\TopsModule::GetRoutes();
}

/**
 * Handles tops/service route
 *
 * @param string $serviceCode
 * @param string $parameter
 *
 * @see \Drupal\tops\TopsModule::GetRoutes();
 */
function tops_service_execute($serviceCode='',$parameter='') {
   \Drupal\tops\TopsModule::ExecuteService($serviceCode, $parameter);
}

function foo () {

}

/**
* Implementation of hook_help()
 *
* Return text for admin page help
**/

function tops_help($path, $arg) {
    \Drupal\tops\TopsModule::GetHelpContent($path,$arg);
}


/**
*  Implement hook_init()
*  Perform TOPS bootstrap tasks
*/
function tops_init() {
    \Drupal\tops\TopsModule::Initialize();
}

/**
* Implement hook_user
* Initialize of update tops user object
*/
 function tops_user($op, &$edit, &$account, $category = null) {
    if ($category=='account' && $op == 'update') {
        $drupalAccount = new \Tops\drupal\TDrupalAccount($account);
        \Drupal\tops\TopsModule::UpdateUser($drupalAccount);
    }
}

/**
 * Implements hook_user_update().
 */
function tops_user_update(&$edit, $account, $category)
{
    if ($category=='account') {
        $drupalAccount = new \Tops\drupal\TDrupalAccount($account);
        \Drupal\tops\TopsModule::UpdateUser($drupalAccount);
    }
}


/**
 * Implements hook_permission().
 */
function tops_permission()
{
    return \Drupal\tops\TopsModule::GetPermissions();
}


