<?php
/**
 * Created by PhpStorm.
 * User: Terry
 * Date: 4/17/2015
 * Time: 5:44 AM
 *
 * Run this script to prepare for deployment.
 *
 *
 */

// Include environment specific path variables
// See environnment.php.example.txt
include(__DIR__.'\environment.php');

// minify css generated by LESS
$minifyCss = "java -jar $yuicompressor $themeroot".'less\style.css  > '.$themeroot.'assets\css\scym-theme.min.css';
echo 'Compressing CSS file...';
exec($minifyCss);
// echo "\n".$minifycss;
echo "\n\nDone\n";